### PR TITLE
more https everywhere

### PR DESCRIPTION
**Pull request by ka7**
.. should help to fix the "mixed content" error messages.
the in the flatter-js-settings .. not 100% sure if the https might bite there or not.

### CODE REVIEW

**Comment by hartwork** [comment]
Hi @ka7, nice one!

Would you mind reverting the feedvalidator part (as their SSL setup is broken) and the whitespace change at the very end of `soap_test.php5`?

Thanks and best, Sebastian

**Comment by ka7** [comment]
about the soap_test.php5.
spooky...  if I open/save/close the file ( gedit, vi, ..) it changes the data. ( adds a 0x000a = utf8-newline )

$ hexdump  soap_test.php5_before | tail -n3; hexdump soap_test.php5 | tail -n3
0000170 700a 6972 746e 725f 2428 626f 296a 0a3b
0000180 3e3f                                   
0000182

0000170 0a3b 700a 6972 746e 725f 2428 626f 296a
0000180 0a3b 3e3f 000a                         
0000185
(also changed already http to https in that file, therefore different length)

**Comment by hartwork** [comment]
This is getting interesting! :)
It seems like the second commit is reverting something else to HTTP as well. Can you revert that revert and make it a single commit again? I haven't checked that 0x000a thing in detail yet, but UTF-8 should be [free of nullbytes (except for code point `U+0000`)](https://en.wikipedia.org/wiki/UTF-8#Description). Maybe the editor thinks it's UTF-16? You could use `git add -p` to get around that trouble hunk if needed.

**Comment by hartwork** [comment]
Small update on `000a`: There is no nullbyte, it's just byte order and hexdump's way of output. Compare these two:
```
# echo 12345 | hexdump
0000000 3231 3433 0a35                         
0000006

# echo 1234 | hexdump
0000000 3231 3433 000a                         
0000005
```

**Comment by ka7** [comment]
argh, i give up on this 0x0a stuff. :-(

**Comment by hartwork** [comment]
Merged and live a https://wnpp.debian.net/ now. Thank you!

**Pull request merged**
